baseURL = 'https://davidwgeddes.github.io/Website/'
languageCode = 'en-US'
languageName = 'English'
title = 'David Geddes'
theme = 'PaperMod'
publishDir = 'docs'

# Output formats
[outputs]
home = ["HTML", "JSON"]

# Markup
[markup.highlight]
lineNos = true
noClasses = false

